### ISSUE TITLE
No way to monitor cache error rates

### ISSUE THREAD

**Issue by kpdecker** [hapijs/catbox#70]
When using `getOrGenerate`, there is no way to monitor cache error rates, performance, etc as the `set` call's handler is eventually pushed to `Hoek.ignore`.

There should be some way of exposing catbox errors at any point in the system and ideally there would be generic ops-level tracking so things like the delay for set calls, etc can be tracked upstream.

**Comment by hueniverse** [comment]
This changes the behavior when generate is successful but cache set fails to always surface the error. It means that operations that have been successful in the past because set errors were ignored are now going to reflect that. It will also block the response until the cache has been updated which might slow things down a bit but will keep the cache more in sync with the requesting logic (this is minor side effect).

**Comment by hueniverse** [comment]
Errors are now surfaced to the callback via #136.
